with customer_orders as (
    -- get all customer orders from intermediate layer
    -- this already has nation names and order revenue calculated
    select * from {{ ref('int_customer_orders') }}
),

final as (
    select
        -- customer identifiers
        customer_id,
        customer_name,
        nation_name,
        market_segment,
        account_balance,

        -- order summary metrics (one row per customer)
        -- total number of orders this customer has placed
        count(distinct order_id)                as total_orders,

        -- total revenue generated by this customer across all orders
        round(sum(order_revenue), 2)            as lifetime_revenue,

        -- average revenue per order for this customer
        round(avg(order_revenue), 2)            as avg_order_revenue,

        -- total number of line items across all orders
        sum(total_line_items)                   as total_items_ordered,

        -- when did this customer place their first ever order
        min(order_date)                         as first_order_date,

        -- when did this customer place their most recent order
        max(order_date)                         as last_order_date,

        -- how many days between first and last order (customer lifetime)
        datediff(
            day,
            min(order_date),
            max(order_date)
        )                                       as customer_lifetime_days

    from customer_orders
    group by
        customer_id,
        customer_name,
        nation_name,
        market_segment,
        account_balance
)

select * from final
order by lifetime_revenue desc